asp.net-core-diploma/TaskTracker.Web/Models/MyTaskViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using TaskTracker.Models;

namespace TaskTracker.Web.Models
{
    public class MyTaskViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime TargetDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string Details { get; set; }
        public bool IsRepeating { get; set; }
        public int? PeriodCode { get; set; }
        public int? Multiplier { get; set; }
        public int? TaskСategoryId { get; set; }
        public int? TaskPriorityId { get; set; }
        public int? ParentTaskId { get; set; }
        public List<FileInfoViewModel> files { get; set; }
        public List<TagInfoViewModel> Tags { get; set; }
        public List<SelectListItem> TagsInSelectControl { get; set; }
        public List<TaskModelBL> SubTasks { get; set; }
        [Display(Name = "TagsList")]
        public long[] TagsIds { get; set; }
        public bool IsFriendTask { get; set; }
        public bool? TaskEditGrant { get; set; } = true;
        public string UserId { get; set; }
    }
}

asp.net-core-diploma/TaskTracker.Web/Controllers/MyTaskController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using TaskTracker.Models;
using TaskTracker.Shared.Interfaces;
using TaskTracker.Web.Interfaces;
using TaskTracker.Web.Models;
using TaskTracker.Web.Services;

namespace TaskTracker.UI.Controllers
{
    [Authorize(AuthenticationSchemes = "TokenAuthenticationScheme")]
    public class MyTaskController : Controller
    {
        private const int PageSize = 3;
        private readonly ILogger<MyTaskController> _logger;
        private readonly IAPIClient _client;
        private readonly IIdentityClient _identityClient;
        private readonly IMyTaskFilterService _filterService;

        public MyTaskController(ILogger<MyTaskController> logger, IAPIClient client, IMyTaskFilterService filterService, IIdentityClient identityClient)
        {
            _client = client;
            _logger = logger;
            _filterService = filterService;
            _identityClient = identityClient;
        }

        public async Task<IActionResult> Index(string start, string end, bool? delay, bool? completed, int categoryId, int priorityId, string pattern, int page = 1, string tagName = "")
        {
            IEnumerable<TaskModelBL> tasks = await _client.Get<List<TaskModelBL>>("api/mytask/list");

            List<MyTaskViewModel> viewModels = new List<MyTaskViewModel>();

            if (tasks != null)
            {
                foreach (var task in tasks)
                {
                    MyTaskViewModel viewModel = new MyTaskViewModel
                    {
                        Id = task.Id,
                        Name = task.Name,
                        StartDate = task.StartDate,
                        TargetDate = task.TargetDate,
                        EndDate = task.EndDate,
                        Details = task.Details,
                        IsRepeating = task.IsRepeating,
                        TaskСategoryId = task.TaskСategoryId,
                        TaskPriorityId = task.TaskPriorityId,
                        ParentTaskId = task.ParentTaskId,
                        files = null,
                        IsFriendTask = task.IsFriendTask
                    };
                    if (task.EndDate == null && completed != true)
                    {
                        viewModels.Add(viewModel);
                    }
                    if (task.EndDate != null && completed == true)
                    {
                        viewModels.Add(viewModel);
                    }

                    List<TaskTagModelBL> taskTag = await _client.Get<List<TaskTagModelBL>>("api/tasktag/fortask/" + task.Id.ToString());
                    if (taskTag != null)
                    {
                        viewModel.Tags = new List<TagInfoViewModel>();
                        foreach (TaskTagModelBL fl in taskTag)
                        {
                            viewModel.Tags.Add(new TagInfoViewModel()
                            {
                                Id = fl.Id,
                                Name = fl.Name
                            });
                        }
                    }
                }
            }
            if (delay == true)
            {
                viewModels = _filterService.FilterTasksByDelay(viewModels);
            }
            if (start != null)
            {
                viewModels = _filterService.FilterTasksByDate(viewModels, start, end);
            }
            if (pattern != null && !pattern.Contains("#"))
            {
                viewModels = _filterService.FilterTasksByName(viewModels, pattern);
            }
            if (categoryId != 0)
            {
                viewModels = _filterService.FilterTasksByCategory(viewModels, categoryId);
            }
            if (priorityId != 0)
            {
                viewModels = _filterService.FilterTasksByPriority(viewModels, priorityId);
            }
            if (!string.IsNullOrEmpty(tagName) || (pattern != null && pattern.Contains("#")))
            {
                viewModels = _filterService.FilterTasksByTagName(viewModels, string.IsNullOrEmpty(tagName) ? pattern.Replace("#", "") : tagName);
            }

            List<TaskCategoryModelBL> categories = await _client.Get<List<TaskCategoryModelBL>>("api/taskcategory");
            List<PriorityModelBL> priorities = await _client.Get<List<PriorityModelBL>>("api/priority");

            categories.Insert(0, new TaskCategoryModelBL { Name = "", Id = 0 });
            priorities.Insert(0, new PriorityModelBL { Name = "", Id = 0 });

            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            ViewBag.Priorities = new SelectList(priorities, "Id", "Name");

            PageMyTaskViewModel pageViewModel = new PageMyTaskViewModel(viewModels.Count, page, PageSize);

            IndexMyTaskViewModel indexViewModel = new IndexMyTaskViewModel()
            {
                MyTasks = viewModels.Skip((page - 1) * PageSize).Take(PageSize).ToList(),
                PageViewModel = pageViewModel
            };

            if (start != null)
            {
                indexViewModel.StartDate = Convert.ToDateTime(start);
            }

            if (end != null)
            {
                indexViewModel.EndDate = Convert.ToDateTime(end);
            }

            if (delay != null)
            {
                indexViewModel.Delay = delay;
            }

            if (completed != null)
            {
                indexViewModel.Completed = completed;
            }

            if (pattern != null && !pattern.Contains("#"))
            {
                indexViewModel.Pattern = pattern;
            }

            if (categoryId != 0)
            {
                indexViewModel.CategoryId = categoryId;
            }

            if (priorityId != 0)
            {
                indexViewModel.PriorityId = priorityId;
            }

            return View(indexViewModel);
        }

        public async Task<IActionResult> Create()
        {
            List<PeriodTypeModelBL> periodTypes = await _client.Get<List<PeriodTypeModelBL>>("api/periodtype");
            List<TaskCategoryModelBL> categories = await _client.Get<List<TaskCategoryModelBL>>("api/taskcategory");
            List<PriorityModelBL> priorities = await _client.Get<List<PriorityModelBL>>("api/priority");

            categories.Insert(0, new TaskCategoryModelBL { Name = "", Id = 0 });
            priorities.Insert(0, new PriorityModelBL { Name = "", Id = 0 });

            ViewBag.Repeat = new SelectList(periodTypes, "Id", "Name");
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            ViewBag.Priorities = new SelectList(priorities, "Id", "Name");

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(MyTaskViewModel model, IFormFile[] uploadedFiles)
        {
            if (ModelState.IsValid)
            {
                TaskModelBL task = new TaskModelBL
                {
                    Name = model.Name,
                    TargetDate = model.TargetDate,
                    Details = model.Details,
                    IsRepeating = model.IsRepeating,
                    Multiplier = model.Multiplier,
                    PeriodCode = model.PeriodCode,
                    ParentTaskId = model.ParentTaskId,
                    files = new List<FileModelBL>()
                };

                if (model.TaskСategoryId != 0)
                {
                    task.TaskСategoryId = model.TaskСategoryId;
                }

                if (model.TaskPriorityId != 0)
                {
                    task.TaskPriorityId = model.TaskPriorityId;
                }

                if(task.IsRepeating==true && task.Multiplier == null)
                {
                    task.Multiplier = 1;
                }

                foreach (IFormFile uploadedFile in uploadedFiles)
                {
                    using (var ms = new MemoryStream())
                    {
                        uploadedFile.CopyTo(ms);
                        var fileBytes = ms.ToArray();
                        FileModelBL fl = new FileModelBL
                        {
                            FileName = uploadedFile.FileName,
                            ContentType = uploadedFile.ContentType,
                            Data = fileBytes
                        };
                        task.files.Add(fl);
                    }
                }

                await _client.Post("api/mytask/create", task);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            TaskModelBL task = await _client.Get<TaskModelBL>("api/mytask/details/" + id.ToString());

            if (task == null)
            {
                return NotFound();
            }
            MyTaskViewModel viewModel = new MyTaskViewModel
            {
                Id = task.Id,
                Name = task.Name,
                StartDate = task.StartDate,
                TargetDate = task.TargetDate,
                Details = task.Details,
                IsRepeating = task.IsRepeating,
                TaskСategoryId = task.TaskСategoryId,
                TaskPriorityId = task.TaskPriorityId,
                Multiplier = task.Multiplier,
                PeriodCode = task.PeriodCode,
                ParentTaskId = task.ParentTaskId,
                TaskEditGrant = task.EditGrant,
                IsFriendTask = task.IsFriendTask
            };

asp.net-core-diploma/TaskTracker.Web/Views/MyTask/AddFriendToTask.cshtml
@model TaskTracker.Web.Models.MyTaskWithFriendViewModel

<h1>Добавить друга к задаче</h1>
<form asp-action="AddFriendToTask" asp-controller="MyTask" method="post">
    <div hidden class="form-group">
        <label asp-for="TaskId">Друзья:</label>
        <input asp-for="TaskId">
    </div>
    <div class="form-group">
        <label asp-for="FriendId">Выберите друга:</label>
        <select asp-items="ViewBag.UserFriends" asp-for="FriendId"></select>
    </div>
    <button type="submit" class="btn btn-primary">Добавить</button>
    &nbsp;&nbsp;<input type="button" class="btn btn-primary" onclick="location.href='../../MyTask/Update/@Model.TaskId'" value="Отмена">
</form>

asp.net-core-diploma/TaskTracker.Web/Views/MyTask/AddSubTask.cshtml
@model TaskTracker.Web.Models.SubTaskViewModel

<h1>Добавление подзадачи</h1>
<form asp-action="AddSubTask" asp-controller="MyTask" method="post">
    <div hidden class="form-group">
        <label asp-for="ParentTaskId">Задача:</label>
        <input asp-for="ParentTaskId">
    </div>
    <div class="form-group">
        <label asp-for="SubTaskId">Выберите подзадачу:</label>
        <select asp-items="ViewBag.SubTasks" asp-for="SubTaskId"></select>
    </div>
    <button type="submit" class="btn btn-primary">Добавить</button>
    &nbsp;&nbsp;<input type="button" class="btn btn-primary" onclick="location.href='../../MyTask/Update/@Model.ParentTaskId'" value="Отмена">
</form>

asp.net-core-diploma/TaskTracker.Web/Views/MyTask/Create.cshtml
@model TaskTracker.Web.Models.MyTaskViewModel

<div class="row">
    <p>
        <h1>Добавление новой задачи</h1>
    </p>    
</div>
<br />
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <form asp-action="Create" asp-controller="MyTask" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Name">Задача:</label>
                    <input asp-for="Name" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="TargetDate">Срок завершения:</label>
                    <input asp-for="TargetDate" type="date" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Details">Описание:</label>
                    <input asp-for="Details" class="form-control">
                </div>
                <div class="form-group form-check">
                    <input id="check" asp-for="IsRepeating" class="form-check-input">
                    <label asp-for="IsRepeating" class="form-check-label">Повторяемая</label>
                </div>
                <div class="form-group">
                    <label>Повторять каждые: </label>
                    <input disabled type="number" asp-for="Multiplier" name="Multiplier">
                    <select disabled asp-items="ViewBag.Repeat" asp-for="PeriodCode" name="PeriodCode"></select>
                </div>
                <div class="form-group">
                    <label asp-for="TaskСategoryId">Категория задачи:</label>
                    <select asp-items="ViewBag.Categories" asp-for="TaskСategoryId"></select>
                </div>
                <div class="form-group">
                    <label asp-for="TaskPriorityId">Приоритет задачи:</label>
                    <select asp-items="ViewBag.Priorities" asp-for="TaskPriorityId"></select>
                </div>
                <br />
                <button type="submit" class="btn btn-primary">Сохранить</button>
                &nbsp;&nbsp;<button type="submit" value="Cancel" name="Cancel" class="btn btn-primary"
                                    formaction="/MyTask/Index" onclick="return confirm('Несохраненные изменения будут утеряны. Уйти со страницы?')">
                    Отмена
                </button>
            </form>
        </div>
        <div class="col-md-3">
            @await Html.PartialAsync("Files")
        </div>
    </div>
</div>

<script>
    document.addEventListener('change', function () {
        var item = event.target

        if (item.tagName === 'INPUT' && item.type === 'checkbox') {
            if ($('input[name="Multiplier"]').prop('disabled') === true
                && $('select[name="PeriodCode"]').prop('disabled') === true) {
                $('input[name="Multiplier"]').prop('disabled', false);
                $('select[name="PeriodCode"]').prop('disabled',false)
            } else {
                $('input[name="Multiplier"]').prop('disabled', true);
                $('select[name="PeriodCode"]').prop('disabled', true)
            }
        }
    })
</script>

asp.net-core-diploma/TaskTracker.Web/Views/MyTask/Index.cshtml
@model TaskTracker.Web.Models.IndexMyTaskViewModel

@addTagHelper *, TaskTracker.Web

<div class="row">
    <div class="col-md-8">
        <p>
            <h1>Список моих задач</h1>
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-7">
        <form class="form-inline" asp-action="Index" asp-controller="MyTask">
            <div class="form-group" hidden>
                <input asp-for="@Model.StartDate" name="start" />
                <input asp-for="@Model.EndDate" name="end" />
                <input asp-for="@Model.Delay" name="delay" />
            </div>
            <div class="form-group">
                <label>Категория </label>&nbsp;
                <select asp-for="@Model.CategoryId" asp-items="ViewBag.Categories" name="categoryId" id="categoryId"></select>&nbsp;
            </div>
            <div class="form-group">
                <label>Приоритет </label>&nbsp;
                <select asp-for="@Model.PriorityId" asp-items="ViewBag.Priorities" name="priorityId" id="priorityId"></select>
            </div>&nbsp;
            <div class="form-group">
                <button type="submit" class="btn btn-outline-secondary">Фильтр</button>&nbsp;<button type="submit" class="btn btn-outline-secondary" onclick="$('select#categoryId').val('');$('select#priorityId').val('');">Сбросить</button>
            </div>&nbsp;
        </form>
    </div>
    <div class="col-md-3">
        <form asp-action="Index" asp-controller="MyTask">
            <div class="input-group mb-3">
                <input type="text" name="pattern" id="pattern" class="form-control" placeholder="Найти задачу или #тег" aria-label="Найти задачу" aria-describedby="button-addon">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon">Найти</button>
                </div>
            </div>
        </form>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-3">
        @await Html.PartialAsync("MyTaskMenu")
    </div>
    <div class="col-md-9">
        <div class="row">
            @foreach (var item in Model.MyTasks)
            {
                <div class="col-md-3">
                    <div class="card @{
                        if (item.IsFriendTask)
                        {
                            @:text-white border-success bg-success 
                        }
                        else
                        {
                            switch (item.TaskPriorityId)
                            {
                                case 4:
                                    @:text-white border-danger bg-danger
                                    break;
                                case 3:
                                    @:text-white border-warning bg-warning
                                    break;
                                case 2:
                                    @:text-white border-info bg-info
                                    break;
                                default:
                                    @:border-light bg-light
                                        break;
                                }
                            }
                        }" style="width: 12rem;">
                        <div class="card-header">
                            @if (item.IsFriendTask)
                            {
                                @:Задача друга
                            }
                            else
                            {
                                @switch (item.TaskPriorityId)
                                {
                                    case 4:
                                        @:Критический
                                        break;
                                    case 3:
                                        @:Высокий
                                        break;
                                    case 2:
                                        @:Низкий
                                        break;
                                    default:
                                        @:Обычный
                                        break;
                                }
                            }
                        </div>
                        <img src="~/pictures/task.png" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">@item.Name</h5>
                            <h6 class="card-subtitle mb-2 text-muted">@item.TargetDate.Date.ToShortDateString()</h6>
                            <p class="card-text">@item.Details</p>
                            @if (item.EndDate == null)
                            {
                                <a asp-action="Update" asp-controller="MyTask" asp-route-id="@item.Id" class="btn btn-primary">Подробнее</a>
                            }
                            else
                            {
                                <button disabled class="btn btn-primary">Подробнее</button>
                            }
                            @await Html.PartialAsync("Tags", item)
                            <br />
                        </div>
                    </div>
                </div>
            }
        </div>
        <br />   
        <page-link page-model="Model.PageViewModel" page-action="Index"
                   page-url-start="@Model.StartDate?.Date.ToShortDateString()" 
                   page-url-end="@Model.EndDate?.Date.ToShortDateString()" 
                   page-url-delay="@Model.Delay" page-url-completed="@Model.Completed"
                   page-url-pattern="@Model.Pattern" page-url-categoryId="@Model.CategoryId" page-url-priorityId="@Model.PriorityId"></page-link>
    </div>
</div>

asp.net-core-diploma/TaskTracker.Web/Views/MyTask/MyTaskMenu.cshtml
@model TaskTracker.Web.Models.IndexMyTaskViewModel

<p>
    <a asp-action="Create" asp-controller="MyTask" class="btn btn-primary">Добавить задачу</a>
</p>

<div class="dropdown">
    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Задачи
    </a>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <a class="dropdown-item" asp-action="Index" asp-controller="MyTask">Все</a>
        <a class="dropdown-item" asp-action="Index" asp-controller="MyTask" asp-route-start="@System.DateTime.Today.ToShortDateString()">На сегодня</a>
        <a class="dropdown-item" asp-action="Index" asp-controller="MyTask" asp-route-start="@System.DateTime.Today.AddDays(1).ToShortDateString()">На завтра</a>
        <a class="dropdown-item" asp-action="Index" asp-controller="MyTask" asp-route-start="@System.DateTime.Today.ToShortDateString()" asp-route-end="@System.DateTime.Today.AddDays(7).ToShortDateString()">На неделю</a>
        <a class="dropdown-item" asp-action="Index" asp-controller="MyTask" asp-route-delay="true">Просрочено</a>
        <a class="dropdown-item" asp-action="Index" asp-controller="MyTask" asp-route-completed="true">Завершены</a>
    </div>
</div>
<br />

<p>Выбрать за период</p>
<form asp-action="Index" asp-controller="MyTask">
    <div class="form-group">
        <input asp-for="@Model.StartDate" type="date" name="start" id="start" class="form-control" />
    </div>
    <div class="form-group">
        <label>по</label>
        <input asp-for="@Model.EndDate" type="date" name="end" id="end" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Выбрать</button>
</form>

asp.net-core-diploma/TaskTracker.Web/Views/MyTask/ReadOnlyFiles.cshtml
@model TaskTracker.Web.Models.MyTaskViewModel
@{
    ViewData["Title"] = "Добавление файла";
}
<h3>Файлы к задаче</h3>
@if (Model != null)
{
    <br />
    <h3>Все файлы</h3>
    <table class="table">
        <tr>
            <td><span style="font-weight:bold">Имя файла</span></td>
            <td><span style="font-weight:bold">Просмотр</span></td>
            <td></td>
            <td></td>
        </tr>
        @if (Model.files != null)
        {
            for (int i = 0; i < Model.files.Count; i++)
            {
                <tr id="tr_@i">
                    <td>@Model.files[i].FileName</td>
                    <td><a href="/files/@Model.Id/@Model.files[i].FileName" target="blank">Просмотр</a></td>
                    <td><input type="hidden" asp-for="files[i].Id" /><input type="hidden" asp-for="files[i].Deleted" /></td>
                </tr>
            }
        }
    </table>
    <br />
}

asp.net-core-diploma/TaskTracker.Web/Views/MyTask/Update.cshtml
@model TaskTracker.Web.Models.MyTaskViewModel

@if (Model.TaskEditGrant == false)
{
    @await Html.PartialAsync("UpdateReadOnlyPartial");
}
else
{
    <div class="row">
        <p>
            <h1>Страница задачи</h1>
        </p>
    </div>
    <br />
    <form asp-action="Update" asp-controller="MyTask" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-3">
                <div class="btn-group-vertical" role="group" aria-label="Button group with nested dropdown">
                    <a asp-action="AddSubTask" asp-controller="MyTask" asp-route-id="@Model.Id" class="btn btn-primary">Добавить подзадачу</a>
                    <div class="btn-group" role="group">
                        <button id="btnGroupDrop2" type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Подзадачи
                        </button>
                        <div class="dropdown-menu" aria-labelledby="btnGroupDrop2">
                            @foreach (var item in Model.SubTasks)
                            {
                                <a asp-action="Update" asp-controller="MyTask" asp-route-id="@item.Id" class="dropdown-item">@item.Name</a>
                            }
                        </div>
                    </div>
                    &nbsp;&nbsp;
                    @if (!Model.IsFriendTask)
                    {
                        <div class="btn-group" role="group">
                            <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Завершить
                            </button>
                            <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                                <a class="dropdown-item" asp-action="Complete" asp-controller="MyTask" asp-route-id="@Model.Id">Текущую задачу</a>
                                <a class="dropdown-item" asp-action="Complete" asp-controller="MyTask" asp-route-id="@Model.Id" asp-route-all="true">Задачу и все повторы</a>
                            </div>
                        </div>
                        <a asp-action="Delete" asp-controller="MyTask" asp-route-id="@Model.Id" class="btn btn-outline-secondary" onclick="return confirm('Вы уверены?')">Удалить</a>
                    }
                </div>
                <br />
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Name">Задача:</label>
                    <input asp-for="Name" class="form-control">
                </div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="TargetDate">Срок завершения:</label>
                    <input asp-for="TargetDate" type="date" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Details">Описание:</label>
                    <input asp-for="Details" class="form-control">
                </div>
                <div class="form-group form-check">
                    <input id="check" asp-for="IsRepeating" class="form-check-input" name="IsRepeating">
                    <label asp-for="IsRepeating" class="form-check-label">Повторяемая</label>
                </div>
                <div class="form-group">
                    <label>Повторять каждые: </label>
                    <input type="number" asp-for="Multiplier" name="Multiplier">
                    <select asp-items="ViewBag.Repeat" asp-for="PeriodCode" name="PeriodCode"></select>
                </div>
                <div class="form-group">
                    <label asp-for="TaskСategoryId">Категория задачи:</label>
                    <select asp-items="ViewBag.Categories" asp-for="TaskСategoryId"></select>
                </div>
                <div class="form-group">
                    <label asp-for="TaskPriorityId">Приоритет задачи:</label>
                    <select asp-items="ViewBag.Priorities" asp-for="TaskPriorityId"></select>
                </div>
                <input hidden asp-for="ParentTaskId" />
                <div class="form-group">
                    <button type="submit" value="Update" name="Update" class="btn btn-primary" formaction="/MyTask/Update/@Model.Id">Сохранить</button>
                    &nbsp;&nbsp;<button type="submit" value="Cancel" name="Cancel" class="btn btn-primary"
                                        formaction="/MyTask/Index" onclick="return confirm('Несохраненные изменения будут утеряны. Уйти со страницы?')">
                        Отмена
                    </button>
                </div>
            </div>
            <div class="col-md-3">
                @await Html.PartialAsync("Files")
                <br />

                <div class="btn-group-vertical" role="group" aria-label="Button group with nested dropdown">
                    @if (!Model.IsFriendTask)
                    {
                        <a asp-action="AddFriendToTask" asp-controller="MyTask" asp-route-id="@Model.Id" class="btn btn-primary">Добавить друга</a>
                    }
                        <div class="btn-group" role="group">
                            <button id="btnGroupDrop2" type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Участники задачи
                            </button>
                            <div class="dropdown-menu" aria-labelledby="btnGroupDrop2">
                                @foreach (var item in ViewBag.friendslist)
                                {       
                                    @string.Format("{0} {1} ({2})", item.FamilyName, item.Name, item.UserName)
                                }
                            </div>
                        </div>
                    </div>

            </div>
        </div>
    </form>
}

<script>
    if ($('input[name="IsRepeating"]').prop('checked') === false) {
        $('input[name="Multiplier"]').prop('disabled', true);
        $('select[name="PeriodCode"]').prop('disabled', true)
    }

    document.addEventListener('change', function () {
        var item = event.target

        if (item.tagName === 'INPUT' && item.type === 'checkbox') {
            if ($('input[name="Multiplier"]').prop('disabled') === true
                && $('select[name="PeriodCode"]').prop('disabled') === true) {
                $('input[name="Multiplier"]').prop('disabled', false);
                $('select[name="PeriodCode"]').prop('disabled', false)
            } else {
                $('input[name="Multiplier"]').prop('disabled', true);
                $('select[name="PeriodCode"]').prop('disabled', true)
            }
        }
    })
</script>